version: '3.9'

services:
  mssql:
    build: database
    restart: always
    container_name: mssql
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD}
      ACCEPT_EULA: ${MSSQL_EULA}
    ports:
      - ${MSSQL_HOST_PORT}:${MSSQL_CONTAINER_PORT}