version: '3.9'

services:

  mssql:
    container_name: mssql
    build: src/mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql:/var/opt/mssql/data

volumes:
  mssql: